
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-10-30T10:11:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "79f7812b0900e35db04021484b9d56ee4415cc6c",
 "version": "0.10.0+744.g79f7812b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
